name: Beauté Élite
favicon: null
layout_spectrum: 0.13627
typography_spectrum: 0.75704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#ef1721'
    - '#4f4f4f'
    - '#808080'
  brandStrength: 0.3086480521596968
  lightness: 0.033687434159219265
  saturation: 0.26586505305022
  rhythmicContrast: 0.3547521897125989
purpose: []
