name: Beauté Élite
favicon: null
layout_spectrum: 0.75643
typography_spectrum: 0.81233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#ef1721'
    - '#4f4f4f'
    - '#808080'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
