name: Beauté Élite
favicon: null
layout_spectrum: 0.28149
typography_spectrum: 0.74109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bebdbb'
    - '#999997'
    - '#e6e6e6'
    - '#8b5f42'
    - '#191a1f'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
